"""add reminder dispatch tracking

Revision ID: 06861fea41fe
Revises: 93bf69911bf2
Create Date: 2026-04-01 11:45:27.899361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06861fea41fe'
down_revision: Union[str, Sequence[str], None] = '93bf69911bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('dispatch_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reminders', sa.Column('last_dispatch_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'last_dispatch_error')
    op.drop_column('reminders', 'dispatch_attempts')
    # ### end Alembic commands ###
