"""initial schema

Revision ID: 6789497f58b0
Revises: 
Create Date: 2026-04-01 10:47:28.489666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6789497f58b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
