"""add invoice lifecycle fields

Revision ID: 7eba593436e3
Revises: f19e56db4bf6
Create Date: 2026-04-01 11:35:22.236437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7eba593436e3'
down_revision: Union[str, Sequence[str], None] = 'f19e56db4bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('issued_at', sa.DateTime(), nullable=False))
    op.add_column('invoices', sa.Column('due_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_invoices_due_at'), 'invoices', ['due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_due_at'), table_name='invoices')
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'due_at')
    op.drop_column('invoices', 'issued_at')
    # ### end Alembic commands ###
