"""add lead qualification fields

Revision ID: 93bf69911bf2
Revises: 7eba593436e3
Create Date: 2026-04-01 11:41:40.380843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93bf69911bf2'
down_revision: Union[str, Sequence[str], None] = '7eba593436e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('priority_score', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('qualified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'qualified_at')
    op.drop_column('leads', 'priority_score')
    # ### end Alembic commands ###
