"""add estimate approval workflow

Revision ID: beb8f8968086
Revises: 06861fea41fe
Create Date: 2026-04-01 12:26:10.481421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'beb8f8968086'
down_revision: Union[str, Sequence[str], None] = '06861fea41fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('status', sa.String(), nullable=False))
    op.add_column('estimates', sa.Column('issued_at', sa.DateTime(), nullable=False))
    op.add_column('estimates', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('estimates', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimates', 'rejected_at')
    op.drop_column('estimates', 'approved_at')
    op.drop_column('estimates', 'issued_at')
    op.drop_column('estimates', 'status')
    # ### end Alembic commands ###
