"""add_job_completion_workflow

Revision ID: d0bd3133fc90
Revises: beb8f8968086
Create Date: 2026-04-01 16:38:16.950904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0bd3133fc90'
down_revision: Union[str, Sequence[str], None] = 'beb8f8968086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('completion_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'completion_notes')
    op.drop_column('jobs', 'completed_at')
    # ### end Alembic commands ###
